# This is given as a sample, you should probably create your own in production
version: '3'

services:
  mongo:
    image: mongo:4
    restart: always
    networks:
      - internal
    volumes:
      - mongo:/data/db:rw

  redis:
    image: redis:4-alpine
    restart: 'always'
    networks:
      - internal

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    restart: always
    networks:
      - internal
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw

  client:
    image: parapass/loadica:client-latest
    build: client
    restart: always
    networks:
      - internal
    ports:
      - 8000:1234

  server:
    image: parapass/loadica:server-latest
    build: server
    restart: always
    depends_on:
      - mongo
      - elastic
      - redis
    networks:
      - internal
    volumes:
      - cdn:/home/node/app/cdn:rw
    env_file:
      - .env
    ports:
      - 3000:3000

  docs:
    image: parapass/loadica:docs-latest
    build: docs
    restart: always
    ports:
      - 5000:80

networks:
  internal:

volumes:
  cdn:
  mongo:
  esdata:
